
#include "src/derpcontext.cpp"
#include "src/derperror.cpp"
#include "src/derpexecnode_binarymath.cpp"
#include "src/derpexecnode.cpp"
#include "src/derpexecnode_function.cpp"
#include "src/derpexecnode_loop.cpp"
#include "src/derpexecnode_unarymath.cpp"
#include "src/derplexer.cpp"
#include "src/derpobject.cpp"
#include "src/derpparser_block.cpp"
#include "src/derpparser.cpp"
#include "src/derpparser_debug.cpp"
#include "src/derpparser_expression.cpp"
#include "src/derpparser_functioncall.cpp"
#include "src/derpparser_function.cpp"
#include "src/derpparser_ifelse.cpp"
#include "src/derpparser_index.cpp"
#include "src/derpparser_loops.cpp"
#include "src/derpparser_statement.cpp"
#include "src/derpparser_value.cpp"
#include "src/derpparser_variabledec.cpp"
#include "src/derpvm_builtinfunctions.cpp"
#include "src/derpvm.cpp"
#include "src/pooledstring.cpp"
#include "src/derpstring.cpp"

